### ISSUE TITLE
Blank screen after entering credentials

### ISSUE THREAD

**Issue by melodyantioho** [npr/pmp-wordpress-plugin#139]
After entering credentials and clicking "Save Changes", I'm left with a blank screen under the headings on the settings page (see screenshot).

The Groups & Permissions, Series, & Properties pages show completely blank screens.

When trying to Pull, the Search page shows up, but I'm unable to search (the wheel keeps spinning).
When trying to Push from a post, the wheels are spinning on the "Push to PMP" box as well.

Any idea what might be going on?

We are running WordPress 4.9.6.

![screenshot](https://user-images.githubusercontent.com/38045348/40804820-67674904-64ea-11e8-838f-59a70c9f7cd8.png)

**Comment by melodyantioho** [comment]
Closing this thread... it was a mistake on my part.

In case anyone else experiences this problem, I was choosing "Sandbox" from the dropdown menu in the plugin settings and then plugging in credentials from a prod account.

**Comment by benlk** [comment]
Thanks for the report, Melody. We'll have a fix for this in the next version of the plugin, which addresses the problem you described here and which other people described in https://github.com/npr/pmp-wordpress-plugin/issues/128. The fix is in pull request https://github.com/npr/pmp-wordpress-plugin/pull/134.
